// src/config.ts
import { ResourceConfig, BuildingType, EventConfig, Qualification } from './types.js';

export const RESOURCE_CONFIGS: ResourceConfig[] = [
  {
    name: 'energy',
    hasMax: true,
    initialCurrent: 40,
    initialMax: 100,
    enabledByDefault: true,
  },
  {
    name: 'oxygen',
    hasMax: true,
    initialCurrent: 40,
    initialMax: 100,
    enabledByDefault: true,
  },
  {
    name: 'money',
    hasMax: false,
    initialCurrent: 1000,
    enabledByDefault: true,
  },
  {
    name: 'population',
    hasMax: true,
    initialCurrent: 0,
    initialMax: 0,
    enabledByDefault: true,
  },
];

export const BUILDING_TYPES: BuildingType[] = [
  {
    id: 'generator',
    name: 'Generator',
    shortName: 'G',
    description: 'Produziert Energie pro Tick.',
    type: 'energie',
    size: { width: 2, height: 2 },
    image:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="10" fill="%23112846"/><path d="M28 8h12l-8 20h10L24 56l6-22H20L28 8Z" fill="%2300f5ff"/></svg>',
    enabled: true,
    cost: [{ resource: 'money', amount: 200 }],
    perTick: [{ resource: 'energy', amount: 12 }],
    maxBonus: [],
    requiredQualifications: ['tech_basic'],
    bonusQualifications: ['energy_specialist'],
    workerMax: 2,
    activeByDefault: true,
  },
  {
    id: 'life_support',
    name: 'Lebenserhaltung',
    shortName: 'L',
    description: 'Verbraucht Energie, erzeugt Sauerstoff.',
    type: 'versorgung',
    size: { width: 1, height: 2 },
    image:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><defs><linearGradient id="g" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="%2336d1a8"/><stop offset="1" stop-color="%2313242e"/></linearGradient></defs><rect width="64" height="64" rx="12" fill="url(%23g)"/><circle cx="32" cy="22" r="10" fill="%2300f5ff" opacity="0.8"/><path d="M22 40h20v8H22z" fill="%2300f5ff" opacity="0.6"/></svg>',
    enabled: true,
    cost: [{ resource: 'money', amount: 300 }],
    perTick: [
      { resource: 'energy', amount: -5 },
      { resource: 'oxygen', amount: 15 },
    ],
    maxBonus: [],
    requiredQualifications: ['life_support_cert'],
    bonusQualifications: ['medic'],
    workerMax: 2,
    activeByDefault: true,
  },
  {
    id: 'habitat',
    name: 'Wohnmodul',
    shortName: 'H',
    description: 'Erhöht maximale Bevölkerung, verbraucht etwas Energie.',
    type: 'wohnen',
    size: { width: 2, height: 2 },
    image:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="%23302744"/><path d="M16 38h32v14H16z" fill="%23ff79c6" opacity="0.65"/><path d="M14 30 32 14l18 16v4H14z" fill="%23ff79c6" opacity="0.85"/></svg>',
    enabled: true,
    cost: [{ resource: 'money', amount: 250 }],
    perTick: [{ resource: 'energy', amount: -3 }],
    maxBonus: [{ resource: 'population', amount: 5 }],
    requiredQualifications: [],
    bonusQualifications: [],
    workerMax: 1,
    activeByDefault: false,
  },
  {
    id: 'energy_storage',
    name: 'Energiespeicher',
    shortName: 'E',
    description: 'Erhöht maximal speicherbare Energie.',
    type: 'speicher',
    size: { width: 1, height: 1 },
    image:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="%232c3b4f"/><path d="M18 16h28v32H18z" fill="%23bd93f9" opacity="0.75"/><path d="M34 22v6h6l-10 14v-6h-6l10-14Z" fill="%23212a36"/></svg>',
    enabled: true,
    cost: [{ resource: 'money', amount: 300 }],
    perTick: [],
    maxBonus: [{ resource: 'energy', amount: 50 }],
    requiredQualifications: ['tech_basic'],
    bonusQualifications: [],
    workerMax: 1,
    activeByDefault: false,
  },
  {
    id: 'oxygen_storage',
    name: 'O2-Tank',
    shortName: 'O',
    description: 'Erhöht maximal speicherbaren Sauerstoff.',
    type: 'speicher',
    size: { width: 1, height: 1 },
    image:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="12" fill="%23162930"/><circle cx="32" cy="28" r="12" fill="%238be9fd" opacity="0.8"/><path d="M22 40h20v8H22z" fill="%238be9fd" opacity="0.6"/></svg>',
    enabled: true,
    cost: [{ resource: 'money', amount: 300 }],
    perTick: [],
    maxBonus: [{ resource: 'oxygen', amount: 50 }],
    requiredQualifications: ['life_support_cert'],
    bonusQualifications: [],
    workerMax: 1,
    activeByDefault: false,
  },
  {
    id: 'dock',
    name: 'Dock',
    shortName: 'D',
    description: 'Ermöglicht Zuzug neuer Bewohner & etwas Einkommen.',
    type: 'logistik',
    size: { width: 3, height: 1 },
    image:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="10" fill="%23341a1f"/><path d="M10 36h44v12H10z" fill="%23ffb86c" opacity="0.8"/><path d="M14 22h36v10H14z" fill="%23ffb86c" opacity="0.6"/></svg>',
    enabled: true,
    cost: [{ resource: 'money', amount: 400 }],
    perTick: [{ resource: 'money', amount: 2 }],
    maxBonus: [],
    requiredQualifications: ['dock_ops'],
    bonusQualifications: ['logistics'],
    workerMax: 2,
    activeByDefault: true,
  },
  {
    id: 'science_lab',
    name: 'Forschungslabor',
    shortName: 'R',
    description: 'Großes Forschungsmodul, schaltet künftige Technologien frei.',
    type: 'forschung',
    size: { width: 3, height: 3 },
    image:
      'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="%23222a48"/><path d="M22 14h8v18l-6 12v6h-6v-8l4-8V14z" fill="%23ff79c6" opacity="0.85"/><path d="M34 14h8v16l6 12v8h-6v-6l-6-12V14z" fill="%238be9fd" opacity="0.85"/><circle cx="32" cy="34" r="6" fill="%23bd93f9"/></svg>',
    enabled: false,
    cost: [{ resource: 'money', amount: 800 }],
    perTick: [{ resource: 'energy', amount: -10 }],
    maxBonus: [],
    requiredQualifications: ['science_basic'],
    bonusQualifications: ['science_advanced'],
    workerMax: 3,
    activeByDefault: true,
  },
];

export const QUALIFICATION_CONFIGS: Qualification[] = [
  {
    code: 'tech_basic',
    title: 'Techniker',
    enabled: true,
    costs: [{ resource: 'money', amount: 80 }],
    learningDuration: 12,
  },
  {
    code: 'energy_specialist',
    title: 'Energie-Spezialist',
    enabled: false,
    costs: [
      { resource: 'money', amount: 150 },
      { resource: 'energy', amount: 10 },
    ],
    learningDuration: 20,
  },
  {
    code: 'life_support_cert',
    title: 'Lebenserhaltung',
    enabled: true,
    costs: [{ resource: 'money', amount: 90 }],
    learningDuration: 14,
  },
  {
    code: 'medic',
    title: 'Sanitäter',
    enabled: false,
    costs: [{ resource: 'money', amount: 120 }],
    learningDuration: 18,
  },
  {
    code: 'dock_ops',
    title: 'Dock-Operator',
    enabled: true,
    costs: [{ resource: 'money', amount: 70 }],
    learningDuration: 10,
  },
  {
    code: 'logistics',
    title: 'Logistikprofi',
    enabled: false,
    costs: [{ resource: 'money', amount: 140 }],
    learningDuration: 16,
  },
  {
    code: 'science_basic',
    title: 'Forscher',
    enabled: false,
    costs: [{ resource: 'money', amount: 200 }],
    learningDuration: 24,
  },
  {
    code: 'science_advanced',
    title: 'Senior-Forscher',
    enabled: false,
    costs: [
      { resource: 'money', amount: 260 },
      { resource: 'energy', amount: 12 },
    ],
    learningDuration: 32,
  },
];

export const EVENT_CONFIGS: EventConfig[] = [
  {
    id: 'low_oxygen_warning',
    title: 'Sauerstoffwarnung',
    message: 'Die Sauerstoffreserven fallen kritisch. Einige Bewohner werden nervös.',
    once: true,
    conditions: [
      { type: 'resource', resource: 'oxygen', comparator: 'lte', value: 20 },
      { type: 'time', ticksGte: 60 },
    ],
    options: [
      {
        id: 'buy_supplies',
        text: 'Notvorräte einkaufen',
        explanation: 'Beruhigt die Crew, kostet aber etwas Geld.',
        effects: [
          { resource: 'money', amount: -120 },
          { resource: 'oxygen', amount: 20 },
        ],
      },
      {
        id: 'ride_it_out',
        text: 'Aussitzen',
        explanation: 'Keine unmittelbaren Maßnahmen. Hoffe auf schnelle Erholung.',
        effects: [],
      },
    ],
  },
  {
    id: 'investor_arrives',
    title: 'Zwielichtiger Investor',
    message: 'Ein Investor bietet dir eine Einlage an – ohne Fragen zu stellen.',
    once: true,
    conditions: [
      { type: 'resource', resource: 'population', comparator: 'gte', value: 10 },
      { type: 'time', ticksGte: 100 },
    ],
    options: [
      {
        id: 'accept_investment',
        text: 'Geld annehmen',
        explanation:
          'Schnelle Liquidität, aber du schuldet ihm einen Gefallen. Das Labor wird freigeschaltet.',
        effects: [{ resource: 'money', amount: 500 }],
        enableBuildings: ['science_lab'],
      },
      {
        id: 'decline_investment',
        text: 'Ablehnen',
        explanation: 'Keine Veränderungen, aber auch keine Bindungen.',
        effects: [],
      },
    ],
  },
];
